@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/user/
?limit=4
&page=1

###
POST {{baseUrl}}/user
Content-Type: application/json

{
    "login": "naeljunior1993",
    "name": "Natanael Junior",
    "password": "123456789",
    "profile": "Admin"

}

###
PATCH {{baseUrl}}/user/f54cf597-4f82-48dc-9a0d-f2a9376cb8ac/
Content-Type: application/json

{
    "login": "Eduardo123"
    
}

###
GET {{baseUrl}}/user/f54cf597-4f82-48dc-9a0d-f2a9376cb8ac/

###
DELETE {{baseUrl}}/user/491785e9-2fe0-407d-8ae3-a0ea30836a99/

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "login": "EdBombadao123",
    "password": "123456789"
}